apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie-nginx
  name: mealie-nginx
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-nginx
  template:
    metadata:
      labels:
        app: mealie-nginx
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.2.0
          name: mealie
          ports:
            - containerPort: 9000
